---@type vim.lsp.Config
return {
  cmd = { 'cspell-lsp', '--stdio' },
  root_markers = {
    '.git',
    'cspell.json',
    '.cspell.json',
    'cspell.json',
    '.cSpell.json',
    'cSpell.json',
    'cspell.config.js',
    'cspell.config.cjs',
    'cspell.config.json',
    'cspell.config.yaml',
    'cspell.config.yml',
    'cspell.yaml',
    'cspell.yml',
  },
  filetypes = {
    'markdown',
    'text',
    'lua',
    'javascript',
    'typescript',
    'typescriptreact',
    'javascriptreact',
    'python',
    'html',
    'css',
    'json',
    'yaml',
  },
}
